### ISSUE TITLE
Does Navigation support parameter

### ISSUE THREAD

**Issue by Razgort** [DevExpress/devextreme-angular-template#106]
Hello guys,

Does your navigation configuration support parameter to call path with like some id or something ?

**Comment by NickMitrokhin** [comment]
Hi,

The template uses [Router](https://angular.io/api/router/Router) for navigation. So, yes, it supports parameters. Take a look at the [Routing & Navigation](https://angular.io/guide/router) help topic to learn how to pass parameters to the [Router.navigate](https://angular.io/api/router/Router#navigate) method.
