### ISSUE TITLE
DevExtreme ThemeBuilder assetsBasePath does not apply

### ISSUE THREAD

**Issue by Estevete** [DevExpress/devextreme-angular-template#126]
Hello, I'm having troubles while importing my metadata json file to ThemeBuilder UI and exporting CSS file. I don't get the fonts & icons url as expected. Does this happen to anyone else?

v19.2.6

**Comment by LexDX** [comment]
Hi Estevete,

We are researching this issue in the [DevExtreme CLI Templates - Themes paths are generated incorrectly in a certain configuration](https://supportcenter.devexpress.com/ticket/details/t862834/devextreme-cli-templates-themes-paths-are-generated-incorrectly-in-a-certain-configuration) report.
