### ISSUE TITLE
Upgrade to 20.2 with scss

### ISSUE THREAD

**Issue by miro-ur** [DevExpress/devextreme-angular-template#147]
When can we expect an upgrade to 20.2 ? Simply upgrading package breaks some visual elements in the app. Would also love to see how to use the new scss styles and customize swatch with new approach.

**Comment by babich-a** [comment]
Hi @miro-ur . We plan to update devextreme version with 20.2.4 release.

**Comment by miro-ur** [comment]
Hello @babich-a. Great news. Looking forward to it !
